#!/usr/bin/env bash
# Rebuilds the off-machine syntax checker used to compile-check Composer
# without the full toolchain. Run inside a Linux container with apt.
#
# It is NOT a build: no linking, no moc, no ctest. What it buys is that a
# translation unit which reaches the Mac has already been through a C++20
# front end with the real HydroCouple / SDK / OGC / GDAL / Qt headers.
#
# Known gaps, all environment rather than code:
#   * Qt here is 6.4. Qt::ColorScheme (6.5+) is supplied by shims/prelude.h;
#     QStyleHints::colorScheme has no shim, so core/composerapplication.cpp
#     and ui/theme/thememanager.cpp cannot be checked.
#   * QRhiWidget (6.7+) is a stub in shims/QRhiWidget — enough for headers
#     that mention it to parse. Nothing that actually drives the RHI
#     (scene/*) is meaningfully checked.
#   * nanoflann is pinned by vcpkg on the Mac; the distro package is older
#     and lacks Tree::IndexType, so shims/ carries v1.6.2's single header.
set -euo pipefail

apt-get update -q
apt-get install -y -q qt6-base-dev qt6-charts-dev qt6-svg-dev \
                      libgdal-dev nlohmann-json3-dev libgtest-dev
curl -sSL -o shims/nanoflann.hpp \
  https://raw.githubusercontent.com/jlblancoc/nanoflann/v1.6.2/include/nanoflann.hpp

# Headers to stage from the user's machine, into these directories:
#   hc/   <- HydroCouple/install/Darwin/include            (8 files)
#   sdk/  <- HydroCoupleSDK/install/Darwin/include         (104 files)
#   ogc/  <- HydroCoupleOgc/include                        (13 files)
#   composer/{include,src,tests/gui} <- the repo itself
#
# composer/include/core/version.h is generated by CMake; synthesise it:
#   #define COMPOSER_VERSION "2.0.0-syntaxcheck"

cat > check.sh <<'EOF'
#!/usr/bin/env bash
S="$(cd "$(dirname "$0")" && pwd)"
QTFLAGS=$(pkg-config --cflags Qt6Widgets Qt6Network Qt6Charts Qt6Svg \
                              Qt6PrintSupport Qt6Concurrent Qt6Xml Qt6Test)
exec g++ -fsyntax-only -std=c++20 -DQT_NO_KEYWORDS \
    -include "$S/shims/prelude.h" \
    -I "$S/composer/include" -I "$S/hc" -I "$S/sdk" -I "$S/shims" \
    -I "$S/ogc" -I "$S/composer/tests/gui" \
    $QTFLAGS $(gdal-config --cflags) "$@" 2>&1
EOF
chmod +x check.sh

# Sweep everything:
#   for f in $(cd composer/src && find . -name '*.cpp'); do
#     out=$(./check.sh composer/src/${f#./} | grep error:) ...
#   done

# ── U4 (2026-09-20): the QRhi gap is closed ──────────────────────────────
#
# This recipe used to record that anything including <rhi/qrhi.h> could not
# be checked — Qt 6.7+ put QRhi in that public header and the container has
# Qt 6.4. That was a packaging gap, not a real one: Qt 6.4 ships the same
# class privately. Two steps close it, and they make scenerenderer.cpp and
# sceneview.cpp CLEAN.
#
#   apt-get install -y qt6-base-private-dev
#
#   mkdir -p "$S/shims/rhi"
#   cat > "$S/shims/rhi/qrhi.h" <<'SHIM'
#   #pragma once
#   #include <QtGui/6.4.2/QtGui/private/qrhi_p.h>
#   SHIM
#
# and add the two private include roots to check.sh (the version-stamped
# directory AND the module directory under it, for each of QtGui and
# QtCore — the private headers include each other both ways round):
#
#   -I /usr/include/x86_64-linux-gnu/qt6/QtGui/6.4.2
#   -I /usr/include/x86_64-linux-gnu/qt6/QtGui/6.4.2/QtGui
#   -I /usr/include/x86_64-linux-gnu/qt6/QtCore/6.4.2
#   -I /usr/include/x86_64-linux-gnu/qt6/QtCore/6.4.2/QtCore
#
# Caveat worth keeping in mind: this checks against 6.4's QRhi, so an API
# that arrived in 6.5-6.7 will read as an error here even though the real
# build is fine. Treat an error in those two files as a question, not a
# verdict — the same way the QStyleHints::colorScheme and QList::assign
# gaps below are read.
