name: Build Docs

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      
    - name: Checkout HydroCouple Repo
      uses: actions/checkout@v4
      with:
        path: HydroCouple
    - name: Checkout HydroCouple Docs Repo
      uses: actions/checkout@v4
      with:
        repository: HydroCouple/hydrocouple.github.io
        ref: dev
        path: hydrocouple.github.io
    - name: Install Graphviz and Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz doxygen

    - name: Build Docs
      run : |
        cd HydroCouple/docs
        doxygen Doxyfile
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/html
