name: Build Docs

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: HydroCouple

    - name: Checkout HydroCouple Docs Repo
      uses: actions/checkout@v3
      with:
        repository: HydroCouple/hydrocouple.github.io
        ref: dev
        path: hydrocouple.github.io
        token: ${{ secrets.API_TOKEN_GITHUB }}
        
    - name: Install Graphviz and Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz doxygen

    - name: Build Docs
      run : |
        cd HydroCouple/docs
        doxygen Doxyfile

    - name: Push Docs to HydroCouple Website Repo
      env:
        USERNAME: github-actions[bot]
        MESSAGE: Documentation update
      run: |
        cp -RT HydroCouple/docs/html hydrocouple.github.io/hydrocoupledocs/html
        cd hydrocouple.github.io
        git config --local user.name "${{ env.USERNAME }}}"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "${{ env.MESSAGE }}"
        git push

      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/html
