name: Build Docs

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: HydroCouple

    - name: Checkout HydroCouple Docs Repo
      uses: actions/checkout@v3
      with:
        repository: HydroCouple/hydrocouple.github.io
        ref: dev
        path: hydrocouple.github.io
        
    - name: Install Graphviz and Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz doxygen

    - name: Build Docs
      run : |
        cd HydroCouple/docs
        doxygen Doxyfile

    - name: Push Docs to HydroCouple Website Repo
      run: |
        cp -RT HydroCouple/docs/html hydrocouple.github.io/hydrocoupledocs/html
        cd hydrocouple.github.io
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Documentation update"
        git push https://$REPO_KEY@github.com/HydroCouple/hydrocouple.github.io 
      env:
        REPO_KEY: ${{ secrets.API_TOKEN_GITHUB }}
        USERNAME: github-actions[bot]

      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/html
