name: Build and Package HydroCouple Interface

on:
  push:
    branches: [ "master" , "dev"]
  pull_request:
    branches: [ "master"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: 6.4.*
  NUGET_FEED_URL: https://nuget.pkg.github.com/HydroCouple/index.json
  NUGET_USER_NAME: ${{ secrets.NUGET_USER_NAME }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/HydroCouple/index.json,readwrite"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            alias: Linux
            shell: bash
            shell_extension: .sh
            env:
              - BUILD_TYPE: Release

          - os: macos-13
            alias: intel-mac
            shell: bash
            shell_extension: .sh
            env:
              - BUILD_TYPE: Release

          - os: macos-latest
            alias: apple-silicon
            shell: bash
            shell_extension: .sh
            env:
              - BUILD_TYPE: Release

          - os: windows-latest
            alias: win64
            shell: cmd
            shell_extension: .bat
            env:
              - BUILD_TYPE: Release

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      

      - name: Install Mono (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          # sudo apt-get update
          # sudo apt-get install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common wget
          # sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          # echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt-get update
          sudo apt-get install -y mono-complete

      - name: Install NuGet
        uses: nuget/setup-nuget@v2

      - name: Verify NuGet Installation
        run: |
          nuget help
    
      - name: Bootstrap vcpkg
        env:
          VCPKG_EXE: ${{ env.VCPKG_INSTALLATION_ROOT }}/vcpkg
        run: |
          echo ${{ env.VCPKG_EXE }}
          echo ${{ env.VCPKG_INSTALLATION_ROOT }}
          # ".$(VCPKG_INSTALLATION_ROOT)/bootstrap-vcpkg${{ matrix.shell_extension }}"
          # ${{ env.VCPKG_EXE }} fetch nuget sources add -Name HydroCouple -Source ${{ env.NUGET_FEED_URL }} -UserName ${{ env.NUGET_USER_NAME }} -ApiKey ${{ env.NUGET_API_KEY }}
          # ${{ env.VCPKG_EXE }} fetch nuget setapikey ${{ env.NUGET_API_KEY }} -Source github

      - name: Configure CMake
        env:
          VCPKG_ROOT:  $(env.VCPKG_INSTALLATION_ROOT)
        run: |
          cmake --preset=default
          cmake -B ${{github.workspace}}/build-${{ matrix.alias }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build-${{ matrix.alias }} --config ${{env.BUILD_TYPE}} --target package

      - name: Test
        working-directory: ${{github.workspace}}/build-${{ matrix.alias }}
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}} 

      - name: Upload Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.alias }}
          path: |
            build-${{ matrix.alias }}/*.tar.gz

