name: Build Docs

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Install Graphviz and Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz doxygen

    - name: Build Docs
      run : |
        cd docs
        doxygen Doxyfile
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/html
