name: Build Docs

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Install Graphviz and Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz doxygen

    - name: Build Docs
      run : |
        cd docs
        doxygen Doxyfile

    
    - name: Push generated docs to website
      uses: nkoppel/push-files-to-another-repository@1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'docs/html'
        destination-username: 'cbuahin'
        destination-repository: 'HydroCouple/hydrocouple.github.io'
        destination-directory: 'hydrocoupledocs/html'
        commit-email: 'calebgh@gmail.com'
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs/html
