name: Build and Deploy HydroCouple Interface Documentation

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

    - name: Checkout HydroCouple Repo
      uses: actions/checkout@v4
      with:
        path: HydroCouple
        persist-credentials: false
    
    - name: Install Graphviz and Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz doxygen
    
    - name: Build Docs
      run : |
        cd HydroCouple/docs
        doxygen Doxyfile
        tar -czvf hydrocouple_docs.tar.gz html
        cd ../../

    - name: Checkout HydroCouple Docs Repo
      uses: actions/checkout@v4
      with:
        repository: HydroCouple/hydrocouple.github.io
        ref: dev
        path: hydrocouple.github.io
        token: ${{ secrets.NUGET_API_KEY }}
        persist-credentials: true

    - name: Push Docs to HydroCouple Website Repo
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name  "github-actions[bot]"
        git config --global credential.helper cache
        rm -rf hydrocouple.github.io/hydrocoupledocs/html
        cp -RT HydroCouple/docs/html hydrocouple.github.io/hydrocoupledocs/html
        cd hydrocouple.github.io
        
        if [ -n "$(git diff --name-only origin/dev)" ]; then
          git add -A
          git commit -m "CI: Updated HydroCouple Docs"
          git push origin dev
        else
          echo "No changes to commit"
        fi
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hydrocouple-docs
        path: HydroCouple/docs/*.tar.gz