name: Build Documentation

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master"]

jobs:
  build_docs:
    name: Build Documentation
    permissions: write-all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:

    - name: Checkout HydroCouple Repo
      uses: actions/checkout@v4 
      with:
        path: HydroCouple
        persist-credentials: false
    
    - name: Install Graphviz and Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz doxygen
    
    - name: Build Docs
      run : |
        cd HydroCouple/docs
        doxygen Doxyfile
        cp CNAME html/
        cd ../../

    - name : Upload Documentation
      uses: actions/upload-pages-artifact@v3
      with:
        path: HydroCouple/docs/html

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Deploy Docs
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: TAR Docs
      run: |
        tar -czvf HydroCouple/docs/hydrocouple_docs.tar.gz HydroCouple/docs/html

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hydrocouple-docs
        path: HydroCouple/docs/*.tar.gz
    