name: Install NuGet

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Install NuGet (Linux)
        if: inputs.os == 'ubuntu-latest'
        run: |
          sudo apt-get install nuget
      
      - name: Install NuGet (macOS)
        if: inputs.os == 'macos-13' || inputs.os == 'macos-latest'
        run: |
          brew install nuget

      - name: Verify NuGet Installation
        run: |
          nuget --version

